name: Issue Created Workflow

on:
  issues:
    types:
      - opened

jobs:
  handle-issue:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Decide if Issue is Inappropriate
        id: check_inappropriate
        run: |
          python decide.py > result.txt
          cat result.txt
        env:
          ISSUE_TITLE: ${{ github.event.issue.title }}
          ISSUE_BODY: ${{ github.event.issue.body }}
          ISSUE_AUTHOR: ${{ github.event.issue.user.login }}

      - name: Read Decision Output
        id: read_decision
        run: |
          result=$(cat result.txt)
          echo "::set-output name=is_inappropriate::$result"

      - name: Label Inappropriate Issues
        if: steps.read_decision.outputs.is_inappropriate == 'true'
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: 'inappropriate'
